### ISSUE TITLE
Установка и настройка

### ISSUE THREAD

**Issue by dmitriyfourier** [semencov/docpad-plugin-mdash#1]
Пожалуйста? добавьте инструкции по установке и настройке плагина через docpad.coffee 

Я правильно понимаю, что установка производится командами, или этого недостаточно, чтобы оно работало?
```
npm install mdash-node
docpad install mdash
```

В файле docpad.coffee для настройки плагина какие опции доступны в template data?

**Comment by semencov** [comment]
Установка через `npm` или сам `docpad`:

```
npm install docpad-plugin-mdash
```
или
```
docpad install mdash
```

Дальше работает и без настроек, просто дёргаем метод `@mdash` в шаблонах, но можно и задать в `docpad.coffee`:

```coffee
docpadConfig =
  plugins:
    mdash:
      default:
        "Text": false
        "OptAlign": false
      title:
        "Text": false
        "OptAlign": true
```

В этом случае, если просто дёргаем `@mdash("Какой-то текст")`, будут использоваться настройки из раздела `default`, а если вторым аргументом задать, например `title`, то настройки будут браться соответствующие: `@mdash("Какой-то текст", 'title')`. Так что можно в `docpad.coffee` можно создавать множество пресетов. Директивы настроек полностью соответствуют оным в `mdash-node`.
